sudo: false
language: 
  - node_js
node_js:
  - "stable"
pipelines:
  default:
    - step:
      name: Validate code
      cache:
        directories:
          - node_modules
      install:
        - npm i -g exp
        - npm install
  branches:
    develop:
      - step:
        name: Validate code
        cache:
          directories:
            - node_modules
        install:
          - npm i -g exp
          - npm install
      - step: test
        script:
          - npm test
      - step: publish to expo.io
        trigger: manual
        script:
          - exp login --username $EXPO_USERNAME --password $EXPO_PASSWORD
          - exp publish