sudo: false
language: 
  - node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
install:
  - npm i -g exp
  - npm install
jobs:
  include:
    - stage: test
      script:
        - npm test
    - stage: publish
      script:
        - exp login --username $EXPO_USERNAME --password $EXPO_PASSWORD
        - exp publish