sudo: false
language: 
  - node_js
node_js:
  - "stable"
install:
  - npm i -g exp
jobs:
  include:
    - stage: install
      cache:
        directories:
          - node_modules
      script:
        - npm install
    - stage: test
      script:
        - npm test
    - stage: publish
      script:
        - exp login --username $EXPO_USERNAME --password $EXPO_PASSWORD
        - exp publish