sudo: false
language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm i -g exp
script:
  - npm test
  - exp login --username $EXPO_USERNAME --password $EXPO_PASSWORD
  - exp publish